"""Finite semantic PowerPoint live-operation vocabulary."""

SLIDES_COM_OPERATIONS = {
    "slides_live_create_presentation",
    "slides_live_list_open",
    "slides_live_get_info",
    "slides_live_get_text",
    "slides_live_get_slide_text",
    "slides_live_find_text",
    "slides_live_insert_text",
    "slides_live_replace_text",
    "slides_live_add_slide",
    "slides_live_delete_slide",
    "slides_live_set_title",
    "slides_live_add_textbox",
    "slides_live_format_text",
    "slides_live_add_shape",
    "slides_live_add_image",
    "slides_live_set_background",
    "slides_live_duplicate_slide",
    "slides_live_reorder_slide",
    "slides_live_set_notes",
    "slides_live_set_slide_size",
    "slides_live_get_masters",
    "slides_live_get_layouts",
    "slides_live_get_placeholders",
    "slides_live_get_notes",
    "slides_live_get_sections",
    "slides_live_get_media",
    "slides_live_apply_template",
    "slides_live_save_template",
    "slides_live_set_layout",
    "slides_live_group",
    "slides_live_ungroup",
    "slides_live_align",
    "slides_live_distribute",
    "slides_live_z_order",
    "slides_live_crop_image",
    "slides_live_rotate_shape",
    "slides_live_add_section",
    "slides_live_delete_section",
    "slides_live_set_slide_visibility",
    "slides_live_set_slide_numbers",
    "slides_live_add_table",
    "slides_live_set_table_cell",
    "slides_live_add_chart",
    "slides_live_add_smartart",
    "slides_live_add_media",
    "slides_live_set_hyperlink",
    "slides_live_set_alt_text",
    "slides_live_set_transition",
    "slides_live_add_animation",
    "slides_live_export_pdf",
    "slides_live_save",
    "slides_screen_capture",
}

SLIDES_COM_READ_OPERATIONS = {
    "slides_live_list_open",
    "slides_live_get_info",
    "slides_live_get_text",
    "slides_live_get_slide_text",
    "slides_live_find_text",
    "slides_live_get_masters",
    "slides_live_get_layouts",
    "slides_live_get_placeholders",
    "slides_live_get_notes",
    "slides_live_get_sections",
    "slides_live_get_media",
}

SLIDES_COM_MUTATING_OPERATIONS = SLIDES_COM_OPERATIONS - SLIDES_COM_READ_OPERATIONS

SLIDES_COM_REQUIRED_ARGS = {
    "slides_live_get_slide_text": {"slide_index"},
    "slides_live_find_text": {"search_text"},
    "slides_live_insert_text": {"text"},
    "slides_live_replace_text": {"find_text", "replace_text"},
    "slides_live_delete_slide": {"slide_index"},
    "slides_live_set_title": {"title"},
    "slides_live_add_textbox": {"text"},
    "slides_live_format_text": set(),
    "slides_live_add_shape": set(),
    "slides_live_add_image": {"image_path"},
    "slides_live_set_background": {"color"},
    "slides_live_duplicate_slide": {"slide_index"},
    "slides_live_reorder_slide": {"slide_index", "to_index"},
    "slides_live_set_notes": {"text"},
    "slides_live_apply_template": {"source_path"},
    "slides_live_save_template": set(),
    "slides_live_set_layout": {"layout"},
    # Grouping accepts either the stable shape names or positive shape indexes;
    # the shared plan validator enforces that at least one selector is present.
    "slides_live_group": set(),
    "slides_live_ungroup": set(),
    "slides_live_align": {"alignment"},
    "slides_live_distribute": {"direction"},
    "slides_live_z_order": {"command"},
    "slides_live_crop_image": set(),
    "slides_live_rotate_shape": {"degrees"},
    "slides_live_add_section": {"name"},
    "slides_live_delete_section": set(),
    "slides_live_set_slide_visibility": {"visible"},
    "slides_live_set_slide_numbers": {"visible"},
    "slides_live_add_table": {"rows", "columns"},
    "slides_live_set_table_cell": {"row", "column", "text"},
    "slides_live_add_chart": {"chart_type"},
    "slides_live_add_smartart": set(),
    "slides_live_add_media": {"media_path"},
    "slides_live_set_hyperlink": {"url"},
    "slides_live_set_alt_text": {"text"},
    "slides_live_set_transition": {"effect"},
    "slides_live_add_animation": {"effect"},
    "slides_live_export_pdf": set(),
    "slides_screen_capture": {"output_path"},
}


def is_read_operation(name: str) -> bool:
    return name in SLIDES_COM_READ_OPERATIONS or name == "slides.inspect"
